#!/usr/bin/python

import time

def countdown(t):
    while t:
      mins,secs = divmod(t, 60)
      timer = '{:02d}:{:02d}'.format(mins,secs)
      print(timer, end="\r")
      time.sleep(5)
      t -= 1
    print('')       #add your text for the countdiwn timer
t = input('Enter the seconds to countdown:')

countdown(int(t))
